[dev]
  functions = './functions'
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build]
  functions = './functions'
  publish = "dist"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev.enviorment]  
  NODE_ENV = "development"
  ENV = "yo"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = false